insert into ad_post (ad_id, title, link, name, ad_group_id) values (1, 'Muriel, or The Time of Return (Muriel ou Le temps d''un retour)', 'http://dummyimage.com/100x121.bmp/dddddd/000000', 'Bitwolf', 3);
insert into ad_post (ad_id, title, link, name, ad_group_id) values (2, 'Myth of the American Sleepover, The', 'http://dummyimage.com/182x170.jpg/dddddd/000000', 'Subin', 6);
insert into ad_post (ad_id, title, link, name, ad_group_id) values (3, 'Mission to Moscow', 'http://dummyimage.com/243x180.png/ff4444/ffffff', 'Veribet', 7);
insert into ad_post (ad_id, title, link, name, ad_group_id) values (4, 'To Have, or Not (En avoir (ou pas))', 'http://dummyimage.com/126x143.png/5fa2dd/ffffff', 'Stim', 19);
insert into ad_post (ad_id, title, link, name, ad_group_id) values (5, 'W.E.', 'http://dummyimage.com/168x233.png/ff4444/ffffff', 'Sub-Ex', 6);
insert into ad_post (ad_id, title, link, name, ad_group_id) values (6, 'White Men Can''t Jump', 'http://dummyimage.com/124x105.jpg/dddddd/000000', 'Stringtough', 4);
insert into ad_post (ad_id, title, link, name, ad_group_id) values (7, 'Thank You, Mr. Moto', 'http://dummyimage.com/164x189.jpg/5fa2dd/ffffff', 'Sub-Ex', 7);
insert into ad_post (ad_id, title, link, name, ad_group_id) values (8, 'Reign of Assassins', 'http://dummyimage.com/168x150.bmp/dddddd/000000', 'Tres-Zap', 8);
insert into ad_post (ad_id, title, link, name, ad_group_id) values (9, 'Divine Secrets of the Ya-Ya Sisterhood', 'http://dummyimage.com/119x111.bmp/dddddd/000000', 'It', 17);
insert into ad_post (ad_id, title, link, name, ad_group_id) values (10, 'Walking and Talking', 'http://dummyimage.com/185x140.png/cc0000/ffffff', 'Alphazap', 16);
insert into ad_post (ad_id, title, link, name, ad_group_id) values (11, 'Ellie Parker', 'http://dummyimage.com/207x227.jpg/ff4444/ffffff', 'Pannier', 15);
insert into ad_post (ad_id, title, link, name, ad_group_id) values (12, 'Secret Life of Zoey, The', 'http://dummyimage.com/236x237.bmp/5fa2dd/ffffff', 'Regrant', 15);
insert into ad_post (ad_id, title, link, name, ad_group_id) values (13, 'Adam & Steve', 'http://dummyimage.com/111x128.bmp/cc0000/ffffff', 'Alpha', 16);
insert into ad_post (ad_id, title, link, name, ad_group_id) values (14, 'Little World of Don Camillo, The (Petit monde de Don Camillo, Le)', 'http://dummyimage.com/242x203.bmp/ff4444/ffffff', 'Transcof', 18);
insert into ad_post (ad_id, title, link, name, ad_group_id) values (15, 'City Zero', 'http://dummyimage.com/116x114.bmp/ff4444/ffffff', 'Sonsing', 16);
insert into ad_post (ad_id, title, link, name, ad_group_id) values (16, 'Harry in Your Pocket', 'http://dummyimage.com/118x231.jpg/dddddd/000000', 'Viva', 16);
insert into ad_post (ad_id, title, link, name, ad_group_id) values (17, 'Daughters of Dolma', 'http://dummyimage.com/189x225.png/cc0000/ffffff', 'Flowdesk', 18);
insert into ad_post (ad_id, title, link, name, ad_group_id) values (18, 'True Crime', 'http://dummyimage.com/143x236.jpg/5fa2dd/ffffff', 'Cardify', 10);
insert into ad_post (ad_id, title, link, name, ad_group_id) values (19, 'Stoned', 'http://dummyimage.com/185x103.png/5fa2dd/ffffff', 'Flexidy', 18);
insert into ad_post (ad_id, title, link, name, ad_group_id) values (20, 'Three on a Match', 'http://dummyimage.com/135x127.jpg/cc0000/ffffff', 'Kanlam', 10);
insert into ad_post (ad_id, title, link, name, ad_group_id) values (21, 'Richard III', 'http://dummyimage.com/184x107.png/dddddd/000000', 'Kanlam', 16);
insert into ad_post (ad_id, title, link, name, ad_group_id) values (22, 'Land of the Dead', 'http://dummyimage.com/217x212.jpg/5fa2dd/ffffff', 'Sonsing', 19);
insert into ad_post (ad_id, title, link, name, ad_group_id) values (23, 'Big Hangover, The', 'http://dummyimage.com/197x114.jpg/5fa2dd/ffffff', 'Lotstring', 16);
insert into ad_post (ad_id, title, link, name, ad_group_id) values (24, 'Fat, Sick & Nearly Dead', 'http://dummyimage.com/154x187.png/dddddd/000000', 'Tres-Zap', 14);
insert into ad_post (ad_id, title, link, name, ad_group_id) values (25, 'Paradise Alley', 'http://dummyimage.com/144x186.png/dddddd/000000', 'Sonair', 19);
insert into ad_post (ad_id, title, link, name, ad_group_id) values (26, 'Dream Boy', 'http://dummyimage.com/241x135.jpg/ff4444/ffffff', 'Tempsoft', 15);
insert into ad_post (ad_id, title, link, name, ad_group_id) values (27, 'Nora''s Will (Cinco días sin Nora)', 'http://dummyimage.com/206x128.bmp/dddddd/000000', 'Subin', 14);
insert into ad_post (ad_id, title, link, name, ad_group_id) values (28, 'Gainsbourg (Vie Héroïque)', 'http://dummyimage.com/246x138.png/cc0000/ffffff', 'Tres-Zap', 11);
insert into ad_post (ad_id, title, link, name, ad_group_id) values (29, 'Small Circle of Friends, A', 'http://dummyimage.com/137x216.png/dddddd/000000', 'Duobam', 8);
insert into ad_post (ad_id, title, link, name, ad_group_id) values (30, 'At Sword''s Point', 'http://dummyimage.com/185x198.jpg/dddddd/000000', 'Biodex', 16);
