insert into advertisement_account (ad_account_id, company_name, industry, permission_id, account_id) values (1, 'Shark Cartilage', 'Business Services', 3, 32);
insert into advertisement_account (ad_account_id, company_name, industry, permission_id, account_id) values (2, 'Value Pharma', 'Electrical Products', 1, 33);
insert into advertisement_account (ad_account_id, company_name, industry, permission_id, account_id) values (3, 'Lucky Super Soft', 'Major Banks', 3, 34);
insert into advertisement_account (ad_account_id, company_name, industry, permission_id, account_id) values (4, 'Allopurinol', 'Savings Institutions',, 2, 31);
insert into advertisement_account (ad_account_id, company_name, industry, permission_id, account_id) values (5, 'Allopurinol', 'Savings Institutions', 3, 35);
insert into advertisement_account (ad_account_id, company_name, industry, permission_id, account_id) values (6, 'health mart ibuprofen', 'Oil & Gas Production', 3, 36);
insert into advertisement_account (ad_account_id, company_name, industry, permission_id, account_id) values (7, 'Entacapone', 'Major Pharmaceuticals', 2, 37);
insert into advertisement_account (ad_account_id, company_name, industry, permission_id, account_id) values (8, 'health mart ibuprofen', 'Oil & Gas Production', 3, 38);
insert into advertisement_account (ad_account_id, company_name, industry, permission_id, account_id) values (9, 'Muscle Ease', 'Finance: Consumer Services', 2, 39);
insert into advertisement_account (ad_account_id, company_name, industry, permission_id, account_id) values (10, 'health mart ibuprofen', 'Oil & Gas Production', 2, 40);
insert into advertisement_account (ad_account_id, company_name, industry, permission_id, account_id) values (11, 'IXEMPRA', 'Major Banks', 2, 29);
insert into advertisement_account (ad_account_id, company_name, industry, permission_id, account_id) values (12, 'Shark Cartilage', 'Business Services', 3, 30);
insert into advertisement_account (ad_account_id, company_name, industry, permission_id, account_id) values (13, 'Enalapril Maleate', 'Multi-Sector Companies', 3, 25);
insert into advertisement_account (ad_account_id, company_name, industry, permission_id, account_id) values (14, 'Vicks VapoRub', 'Major Chemicals', 2, 24);
insert into advertisement_account (ad_account_id, company_name, industry, permission_id, account_id) values (15, 'Vicks VapoRub', 'Major Chemicals', 1, 23);
insert into advertisement_account (ad_account_id, company_name, industry, permission_id, account_id) values (16, 'Vicks VapoRub', 'Major Chemicals', 1, 21);
insert into advertisement_account (ad_account_id, company_name, industry, permission_id, account_id) values (17, 'Idamycin PFS', 'Coal Mining', 3, 22);
insert into advertisement_account (ad_account_id, company_name, industry, permission_id, account_id) values (18, 'Allopurinol', 'Savings Institutions', 2, 26);
insert into advertisement_account (ad_account_id, company_name, industry, permission_id, account_id) values (19, 'Midodrine HCl', 'Business Services', 2, 27);
insert into advertisement_account (ad_account_id, company_name, industry, permission_id, account_id) values (20, 'Shark Cartilage', 'Business Services', 3, 28);